### ISSUE TITLE
Return sends you back one page

### ISSUE THREAD

**Issue by sashamaryl** [codeforboston/cliff-effects#151] opened 2017-11-02 20:00 UTC
﻿

### Images:
None

### Replicate:
1. Place cursor in any entry field on any page. (Does not matter if it has date or not.)
2. Hit return.

### Result I'd Expect:
 - Data would be "entered" and cursor would go to the next field.

### Actual Result:
 - User is returned to previous page. (No data is lost in any field.)

### Environment:
Operating system and version: 2008 macbook running Lubuntu 16.04
Browser type and version: Chromium, 62.0.3202.62 (Official Build)

App version or commit id at the time:
eb8bd79

**Comment by donblair30** [comment] 2017-11-02 20:02
Thanks Sasha!  I'll plan to take a crack at this.

**Comment by knod** [comment] 2017-11-16 17:30
I believe the issue is a normal html one. I think it'd be best to tackle this by looking at the html `tab-index` attribute.

**Comment by knod** [comment] 2017-11-21 20:39
Fixed by #215

**Closed by knod** 2017-11-21 20:39 UTC
Labels: bug
