### ISSUE TITLE
MOD:  "Household Annual Income" Page Percentages

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#12] opened 2017-09-06 00:56 UTC
* [x] Verify CALC of "% of Federal Poverty Level"
* [x] Verify SOURCE of "% of Federal Poverty Level"
* [x] Replace "% of State Median Income" with "Area Median Income"
* [x] Switch phrasing of title from "% of Federal Poverty Level" -> "Federal Poverty Level Percentage".  Do the same for State Med level.
* [ ] Add reference to source of calc. info, incl. year, as clear linked text right underneath associated %ages in comment in codebase

**Comment by danaher2** [comment] 2017-09-06 01:11
Please provide a mockup of how the percentages should look with the references below.

**Comment by lianilychee** [comment] 2017-09-06 16:38
![image](https://user-images.githubusercontent.com/6895034/30123496-2d16b490-9300-11e7-957e-d26f49feef3c.png)

**Comment by lianilychee** [comment] 2017-09-06 16:42
![image](https://user-images.githubusercontent.com/6895034/30123623-a371fce4-9300-11e7-8455-53ec8126c43a.png)

`2010 Nat'l Census data` is stand-in text for the actual sources.

**Comment by knod** [comment] 2017-09-07 19:49
@lianilychee: Wouldn't it be more important to show the expiration date of the document?

**Technical notes:**
- If so, maybe we can use that nifty expiration date idea to fill in things like dates
- Either way, we may want to make the same type of provisions for where the data came from. For example, return a `sources` object as part of the result. Ex:
```js
result.sources = {
  primary: {
    label: "2010 National Census Data",
    link: "http://national-census-data.com" // or an html string or a React component
  },
  // ...
}
```

**Comment by AnnieLa** [comment] 2017-09-20 00:25
https://www.zanebenefits.com/blog/2017-federal-poverty-level-guidelines 

Use the data found on this blog as the basis for federal poverty levels by household size for 2017

**Comment by zzyyfff** [comment] 2017-09-20 00:47
Area Median Income calculation resources:

https://www.huduser.gov/portal/datasets/il.html#2017_data
https://www.huduser.gov/portal/datasets/il/il17/HUD-sec8-FY17.pdf

**Comment by lianilychee** [comment] 2017-09-20 00:52
@knod comment obsolete now; we just removed the citation from the front-end.

**Comment by knod** [comment] 2017-09-20 11:07
@lianilychee: If you no longer want the citation, could you remove it from the list of things to do? It's #5, right?

**Comment by knod** [comment] 2017-09-20 13:18
A note: We can't figure out Area Median Incomes in the way we can figure out State Median Incomes and Federal Poverty Levels. Area median incomes will be either 30%, 50%, or 80%. Is that still useful?

**Comment by zzyyfff** [comment] 2017-09-20 14:05
@knod Are you using all the documents listed at the links I posted, Area Median Income calculation resources? Which document are you using?

Any percentage can be converted into 100% and 100% can be converted into any percentage.

**Comment by knod** [comment] 2017-09-20 21:40
@zzyyfff: (bottom paragraph may make this moot) I used the documents at those links and the table data from 2017 is currently the `AREA_MEDIAN_INCOME_LIMITS_MA_2017` object in the data for Massachusetts. The issue is that they're not actually using percents. They use percents and then adjust them in various ways to do with area, past data, possibly judgement calls they make. If you want a more in-depth description, the second link you listed has those details. When you actually use math to calculate the percents, those calculated values don't line up with the values in their table. If we show their calculated percent, we may end up with a situation where the tool will show that they're below the 50% mark for their area median income, but the benefit program itself wouldn't consider them to be a 'very low income' (below 50%) household.

It occurs to me, though, that I'm not sure how useful it is to show that value. That value was being used to calculate eligibility for Section 8 housing vouchers, but we're no longer determining eligibility. We're now calculating benefits for people who are already in the program and that value isn't used to calculate benefits. I don't think it's being used for any other program either.

**Comment by knod** [comment] 2017-09-20 21:41
For now, I've hidden that value until we decide what to do with it. Don't want it to slip between the cracks.

**Comment by knod** [comment] 2017-09-30 17:37
How about 'Federal Poverty Level: n%'. That seems less ambiguous to me.

**Comment by knod** [comment] 2017-10-30 17:52
First question: Do we really want to show percent poverty level? I'm still unsure of the utility of that. I've put it in the ['Questions'](https://docs.google.com/document/d/13kb1hsxMi6pN9oAUGsTatDz4OSX5IeDLF9B-ddPjMCk/edit#heading=h.xpa7dq1tkm3n) document.

Second question: If we do want it, then I'm not sure what info should be linked. We can provide a link to the data tables, but I'm not sure what we mean by 'calculations'. Could someone clarify?

If we can answer those questions, these changes can be implemented and we can close the issue.

**Comment by knod** [comment] 2017-11-16 17:29
Closing - I believe this is no longer desired.

**Closed by knod** 2017-11-16 17:29 UTC
Labels: discussion needed, feature
